version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432 
 
  consul:
    image: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net
  
  event-scheduler:
    build: 
      context: ..
      dockerfile: event-scheduler/Dockerfile
    image: microservices/event-scheduler:1.0
    environment: 
      - EVENT_SERVICE_PORT=8082
      - CONSUL_HTTP_ADDR=consul:8500  
    ports: 
      - "8082:8082"
    depends_on:
      - consul
      - db
    links:
      - db
    networks:
      - sky-net

  email-service:
    build: 
      context: ..
      dockerfile: email-service/Dockerfile
    image: microservices/email-service:1.0
    environment: 
      - EMAIL_SERVICE_PORT=8083
      - CONSUL_HTTP_ADDR=consul:8500 
    ports: 
      - "8083:8083" 
    depends_on:
      - consul
    networks:
      - sky-net
networks:
  sky-net:
    driver: bridge
